version: 1.0.{build}
branches:
  only:
  - mingw
skip_tags: true
image: Ubuntu1804
clone_depth: 1
environment:
  BINTRAY_APIKEY:
    secure: N8apSeUvATWU5hEc4zPdFdvn/crZ/8CykmK1WEOhPQCGsyLoetzWtfXLf8u2il+n
  VIRUSTOTAL_APIKEY:
    secure: l4MvUDgcJwFhGgXoBCxEhrXG+2IQJBGJPApzF+5xS6fNDAJP6s8WgeH60IKqeLCO4LZwiLUuCjbBHSxDIOLBPGyyBcsMBwnh/ug7l7qQkBU=
  GPG_PASSPHRASE:
    secure: Gw7LYl7JzIn7UOjOtdZv7g==
build_script:
- sh: >-
    export DOCKER_IMAGE='debian:testing'

    time docker pull "${DOCKER_IMAGE}"

    time docker run -v "$(pwd):$(pwd)" -w "$(pwd)" \
      --env-file <(env | grep -E '^(APPVEYOR_|BINTRAY_|GPG_|VIRUSTOTAL_|CODESIGN_|DEPLOY_|CC|GITLAB_|CI_)') \
      "${DOCKER_IMAGE}" \
      sh -c ./mingw/build/_ci-linux-debian.sh
test: off
artifacts:
- path: mingw/build/*-*-mingw*.*
- path: mingw/build/all-mingw*.*
- path: mingw/build/hashes.txt
deploy: off