---
# yamllint disable rule:line-length
branches:
  only:
    - mingw
notifications:
  email: false
git:
  depth: 8
  quiet: true
language: c

matrix:
  include:
    - os: linux
      dist: bionic
      sudo: required
      group: edge
      compiler: gcc
      services: [docker]
      env: DOCKER_IMAGE=debian:testing

script:
  - |
    if [ "${TRAVIS_OS_NAME}" = 'linux' ]; then
      time docker pull "${DOCKER_IMAGE}"
      time docker run -it -v "$(pwd):$(pwd)" -w "$(pwd)" \
        --env-file <(env | grep -E '^(TRAVIS_|BINTRAY_|GPG_|VIRUSTOTAL_|CODESIGN_|DEPLOY_|CC)') \
        "${DOCKER_IMAGE}" \
        sh -c ./mingw/build/_ci-linux-debian.sh
    fi
